### ISSUE TITLE
Correct R2Devops sponsor logo

### ISSUE THREAD

**Issue by Totara-thib** [Volcamp/volcamp.github.io#54]
Hi,

It seems that our R2Devops logo was altered when converting it to a white version.

Please find the correct logo attached.

![Group 289483](https://github.com/user-attachments/assets/d28debfc-dc30-4f39-b82e-c7287681beb2)
![Group 289485](https://github.com/user-attachments/assets/d3079bee-cfd7-4968-b6f6-0b9202066fef)
![Group 289485](https://github.com/user-attachments/assets/df807088-1478-4c40-a979-6512c3dd675e)
![Group 289483](https://github.com/user-attachments/assets/129be6b9-256b-4bcf-837f-260f45eb77d9)

**Comment by khrys63** [comment]
Hi, I just patched, thx for the new logo.

**Comment by khrys63** [comment]
online
